wheel_radius: 0.125
wheel_width: 0.040
wheel_base: 0.322
wheel_tread: 0.322
vehicle_mass: 5000.0
vehicle_length: 0.450
vehicle_width: 0.350
vehicle_height: 0.350
minimum_turning_radius: 0.75
maximum_steering_angle: 97.3 #deg
